### ISSUE TITLE
Issue with show() in 3D scaled interpolations

### ISSUE THREAD

**Issue by natschil** [JuliaMath/Interpolations.jl#270] opened 2018-11-18 10:45 UTC
The following throws an error in `show()`, even though (as far as I can tell) the interpolation object gets constructed correctly

```
using Interpolations
scale(interpolate(zeros(10,10,10),BSpline(Cubic(Free(OnGrid())))),2:11,2:11,2:11)
```

It works in 2D, and if the scaling ranges are 1:10.

**Comment by timholy** [comment] 2018-11-18 11:37
Duplicate of #260.

**Closed by timholy** 2018-11-18 11:37 UTC
