### ISSUE TITLE
why a subtype of AbstractArray?

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/Interpolations.jl#345] opened 2019-12-05 21:14 UTC
Currently, you have `AbstractInterpolation <: AbstractArray` ([here](https://github.com/JuliaMath/Interpolations.jl/blob/e547610fabcb7f4af8b049ce62c5de08895f8461/src/Interpolations.jl#L49)).

This doesn't make sense to me, since it doesn't support `getindex` and generally doesn't act like an array.

(Though it would be nice to expose an iterator for the knots etc.)

**Comment by timholy** [comment] 2019-12-05 23:16
This package used to have a `getindex`-based interface, but we've started transitioning away from it. It's mostly a question of someone sitting down and finishing this.

Duplicate of #242.

**Closed** 2019-12-06 02:50 UTC
