### ISSUE TITLE
ERROR: UndefVarError: TH not defined

### ISSUE THREAD

**Issue by jeff-regier** [JuliaMath/Interpolations.jl#180] opened 2017-09-20 02:43 UTC
I'm getting an error message from a call to `hessian`, though I think I've set everything up correctly. This happens with both the latest released version of Interpolations.jl as well as master.

```
julia> A = randn(10,10);

julia> itp = interpolate(A, BSpline(Cubic(Line())), OnGrid());

julia> hessian(itp, 5., 5.,)
ERROR: UndefVarError: TH not defined
Stacktrace:
 [1] hessian(::Interpolations.BSplineInterpolation{Float64,2,Array{Float64,2},Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line}},Interpolations.OnGrid,1}, ::Float64, ::Float64) at /home/jeff/.julia/v0.6/Interpolations/src/b-splines/indexing.jl:160
```

**Comment by timholy** [comment] 2017-12-06 10:59
Sorry you never got a response to this. Likely a duplicate of #122. It would be great to get a fix for this from someone who uses hessians.

**Closed by timholy** 2017-12-06 10:59 UTC
